### ISSUE TITLE
Run patch on ubuntu 16.04

### ISSUE THREAD

**Issue by Bluehexagon433** [francoism90/HVR-5500#2]
Hi can you provide a short description to use this patch in the terminal? I´m a beginner with patch and firmeware etc... an i need help to use my tv cart hvr 5500 under linux ubuntu 16.04.

**Comment by francoism90** [comment]
I'm sorry, not having this card anymore and don't think this patch is compatible with Linux 4.12/4.14 anymore.

You better ask for support on [LinuxTV](https://linuxtv.org/), maybe someone has already provided a new patch. However if I'm not mistaken it should already be supported.

Good luck and thanks for the interests.
